export const Label = {
    formUserTitle: (status) => { return `${status} ${Label.USER}` },
    USER: "User",
    USERNAME: "Username",
    EMAIL: "Email",
    TYPE: "Type",
    RESIDENT: "Resident",
    OWNER: "Business Owner",
    ORGANIZER: "Organizer",
    PASSWORD: "Password",
    INTERESTS: "Interests",
    LOCATION: "Location",
    PARTICIPATION: "Participation",
    SUBMIT: "Submit",
    CREATE: "Create",
    UPDATE: "Update",
    UPDATEVOLUNTEER: "Update Volunteer",
    ERROR: "Error",
    SUCCESS: "Success"
}