export const Label = {
    formEventTitle: (status) => { return `${status} ${Label.EVENT}` },
    EVENT: "Event",
    CREATE: "Create",
    UPDATE: "Update",
    TITLE: "Title",
    DESCRIPTION: "Description",
    SUMMARY: "Summary",
    TYPE: "Type",
        WORKSHOP: "Workshop",
        MEETUP: "Meet Up",
        CLEAN_UP_DRIVE: "Clean-Up Drive",
    EVENT_START_END_DATES: "Event's start and end dates",
        START_DATE: "Start Date",
        END_DATE: "End Date",
    PRICE: "Price",
        DOLLAR_SIGN: "$",
        TRAILING_AMT: ".00",
    LOCATION: "Location",
    SUBMIT: "Submit",
    BACK: "Back",
    ERROR: "Error",
    SUCCESS: "Success"
}