export const Label = {
    setTitle: (name) => { return `Welcome ${name}` },
    HOME: "Home",
    EVENTS: "Events",
    REGISTER: "Register",
    LOGOUT: "Logout",
    LOGIN: "Login",
    LOADING: "Loading...",
    DASHBOARD: "Dashboard",
    NEWS: "News",
    ALERT: "Alert",
    REQUEST: "Request",
    LEARN_MORE: "Learn More",
    LISTING: "Business Listings",
    BACK: "Back",
    TYPE: "Type",
    EVENT_DATE: "Event Date(s)",
    LOCATION: "Location",
    PRICE: "Price",
    WELCOME: "Welcome",
    NEIGHBORHOOD_WATCH: "Neighborhood Watch!",
    MAIN_SUBTITLE: "Be part of our community!",
    CONNECT_TODAY: "CONNECT TODAY",
    REGISTER_NOW: "Register Now",
    ABOUT_US: "About Us",
    ABOUT_US_TEXT: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id posuere turpis. Ut dolor nibh, dictum eleifend pellentesque sit amet, eleifend sed turpis. Sed nulla ipsum, eleifend consequat rutrum in, laoreet vitae metus. Etiam pharetra, sapien ut laoreet efficitur, dolor tellus eleifend leo, sit amet ultrices lorem sem vitae quam. Aliquam sodales, quam semper tincidunt lobortis, est leo fringilla felis, eget condimentum leo est id dui. Duis quis lacus ullamcorper, feugiat purus non, varius sapien. Vivamus in turpis eu elit lacinia sodales sit amet a nibh.",
    UPCOMING_EVENT: "UPCOMING EVENTS",
    COPYRIGHT: "2025 Group 9",
    CREATE_LISTING: "Create/Update Business Listings",
    VIEW_LISTINGS: "View Business Listings",
}