export const Label = {
    setTitle: (name) => { return `Welcome ${name}` },
    HOME: "Home",
    EVENTS: "Events",
    REGISTER: "Register",
    LOGOUT: "Logout",
    LOGIN: "Login",
    LOADING: "Loading...",
    DASHBOARD: "Dashboard",
    NEWS: "News",
    ALERT: "Alert",
    REQUEST: "Request",
    LEARN_MORE: "Learn More",
    LISTING: "Business Listings",
    BACK: "Back",
    TYPE: "Type",
    EVENT_DATE: "Event Date(s)",
    LOCATION: "Location",
    PRICE: "Price",
    WELCOME: "Welcome",
    CLOSE: "Close"
}