export const Label = {
    setNewsTitle: (status) => { return `${status} News` },
    setRequestsTitle: (status) => { return `${status} Request` },
    setAlertTitle: (status) => { return `${status} Alert` },
    ERROR: "Error",
    HEADLINE: "Headline",
    SUMMARY: "Summary",
    NEWS: "News",
    EXPIRY_DATE: "Expiry Date",
    BACK: "Back",
    SUBMIT: "Submit",
    CREATE: "Create",
    UPDATE: "Update",
    TITLE: "Title",
    TYPE: "Type",
    HELP: "Help",
    MAINTENANCE: "Maintenance",
    ACCOMMODATION: "Accommodation",
    DONATION: "Donation",
    REQUEST: "Request",
    SUCCESS: "Success",
    SUBTITLE: "Subtitle",
    BUSINESS_PAGE_TITLE: "Create/Update Business Listing",
    VIEW_BUSINESS_LISTING_PAGE_TITLE: "View Business Listings",
    BUSINESS_TICKET_ID:"* Business Listing Ticket ID.",
    BUSINESS_TICKET_ID_DESCRIPTION: "* Business Listing Ticket ID. Please keep this for your records.",
    BUSINESS_NAME: "* Business Name",
    ADDRESS: "* Address",
    BUSINESS_DESCRIPTION: "* Business Description",
    BUSINESS_PHONE: "* Phone Number",
    IMAGE_LIST: "Image List",
    BUSINESS_DEALS: "Deals",
    BUSINESS_DEALS_DESCRIPTION: "Enter any deals or offers that your business is offering.",
}