export const Label = {
    setNewsTitle: (status) => { return `${status} News` },
    setRequestsTitle: (status) => { return `${status} Request` },
    setAlertTitle: (status) => { return `${status} Alert` },
    ERROR: "Error",
    HEADLINE: "Headline",
    SUMMARY: "Summary",
    NEWS: "News",
    EXPIRY_DATE: "Expiry Date",
    BACK: "Back",
    SUBMIT: "Submit",
    CREATE: "Create",
    UPDATE: "Update",
    TITLE: "Title",
    TYPE: "Type",
    HELP: "Help",
    MAINTENANCE: "Maintenance",
    ACCOMMODATION: "Accommodation",
    DONATION: "Donation",
    REQUEST: "Request",
    SUCCESS: "Success",
    SUBTITLE: "Subtitle",
    BUSINESS_PAGE_TITLE: "Create/Update Business Listing",
    VIEW_BUSINESS_LISTING_PAGE_TITLE: "View Business Listings",
    BUSINESS_TICKET_ID:"Business Listing Ticket ID.",
    BUSINESS_TICKET_ID_DESCRIPTION: "* Business Listing Ticket ID. Please keep this for your records.",
    BUSINESS_NAME: "Business Name",
    BUSINESS_NAME_DESCRIPTION: "* Business Name. Please include the business name.",
    ADDRESS: "Address",
    ADDRESS_DESCRIPTION: "* Enter Address. Please include the city and province.",
    BUSINESS_DESCRIPTION: "Business Description",
    BUSINESS_DESCRIPTION_DESCRIPTION: "* Business Description. Please include the business description.",
    BUSINESS_PHONE: "Phone Number",
    BUSINESS_PHONE_DESCRIPTION: "* Phone Number. Please include the business phone number.",
    IMAGE_LIST: "Image List",
    BUSINESS_DEALS: "Deals",
    BUSINESS_DEALS_DESCRIPTION: "Enter any deals or offers that your business is offering.",
    DELETE_BTN: "Delete",
    ENTER_REVIEW_DESCRIPTION: "Please enter your anonymous and *permanent* review here.",
    COPYRIGHT: "2025 Group 9"
}