export const Message = {
    INVALID_DATE: "The date entered is not in the following format: MM/DD/YYYY",
    INVALID_FORM: "There are some missing information. Please, complete the form.",
    ENTER_A_HEADLINE: "Enter a headline",
    ENTER_A_SUMMARY: "Enter a summary",
    ENTER_THE_NEWS: "Enter the news",
    ENTER_AN_EXPIRY_DATE: "Enter an expiry date",
    ENTER_A_TITLE: "Enter a title",
    SELECT_A_TYPE: "Select a type",
    ENTER_A_REQUEST: "Enter a request",
    TRY_AGAIN: "An error occurred. Try again.",
    REQUEST_SAVED_SUCCESSFULLY: "Your request has been saved successfully.",
    NEWS_SAVED_SUCCESSFULLY: "Your news has been saved successfully.",
    ALERT_SAVED_SUCCESSFULLY: "Your alert has been saved successfully.",
    BUSINESS_LISTING_SAVED_SUCCESSFULLY: "Your business listing has been created successfully.",
    BUSINESS_LISTING_SAVE_UNSUCCESSFULLY: "Your business listing has been nnot been created successfully.",
    PHONE_NUMBER_INVALID: "The phone number must be in XXX-XXX-XXXX format.",
    BUSINESS_LISTING_UPDATED_SUCCESSFULLY: "Your business listing has been updated successfully.",
    MISSING_FIELDS: "Please enter all fields with an asterisk (*)",
    NO_BUSINESS_LISTINGS_TO_DISPLAY: "There are no business listings to display.",
    REVIEW_SUCCESSFUL: "Your review was sent successfully.",
    REVIEW_NOT_SUCCESSFUL: "Your review was sent successfully.",
    REVIEW_EMPTY: "Please enter a review before posting.",
    NO_BUSSINESS_LISTING_MATCH: "No business listing match your search.",
}